openapi: 3.0.3
info:
  title: Wallet management
  version: 1.0.0
  description: STD22026_STD22020
servers:
  - url: https://wallet.com
tags:
  - name: Accounts
    description: Operations related to accounts
  - name: Transactions
    description: Operations related to transactions
  - name: Currencies
    description: Operations related to currencies
paths: